### ISSUE TITLE
Add support for moderators

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/open-prices#182]
Moderators are special users that will be allowed to delete/update prices or proofs of other users.
This is necessary to ensure database quality.

Tasks:
- [x] create a new `is_moderator` field in the `users` table : #183
- [x] allow moderators to edit proofs : #235 
- [x] allow moderators to delete proofs (without prices) : #197
- [x] allow moderators to edit prices : #259 
- [x] allow moderators to delete prices : #260

**Comment by teolemon** [comment]
FYI https://github.com/openfoodfacts/openfoodfacts-server/pull/9918
