### ISSUE TITLE
Location : allow for Online Stores (e.g. for Open Products Facts)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/open-prices#317]
### Problem

- I was trying to showcase Open Prices for Open Products Facts by adding a price for my late Nexus S, which I bought from the Google Store online
- Make it possible to add the URL of an online store (or a product page)

### Todo

- [x] add a new `Location.type` field : OSM, ONLINE
- [x] add a new `Location.website_url` field (or other name ?)
- [x] Location model validation on save (url should be valid, add https if missing)
- [x] Allow creating prices with a `location_id` : #527
- [x] Allow creating proofs with a `location_id` : #528

Frontend integration: see https://github.com/openfoodfacts/open-prices-frontend/issues/965

**Comment by raphodn** [comment]
Slack discussion : https://openfoodfacts.slack.com/archives/C02Q6KM7F/p1725446418334189

### Naming

- `online_url` (confusion with online/offline ?) vs `website_url` vs `retailer_url` (too restrictive ?)

### Todo

- [ ] add a new `Location.type` field : OSM, WEBSITE
- [ ] add a new `Location.website_url` field (or other name ?)
- [ ] Location model validation on save (url should be valid)
- [ ] the `Price` model currently stores a `location_osm_id` & `location_osm_type`. should we sunset these fields ? Make the `location_id` mandatory ? Or only if `proof_id` is not given ?

**Comment by raphodn** [comment]
Should we ask the delivery cost in an extra field ?

for instance the latest receipt I added: https://prices.openfoodfacts.org/proofs/23569
