### ISSUE TITLE
Location: Store the OSM POI version (for future update)

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices#388]
### Story

When a new price location is provided, we only fetch basic POI data from OSM. But this POI can be updated in the future, or even deleted. We need to have a mechanism to update these POI, or at least know which version we have in OP.

Slack thread : https://openfoodfacts.slack.com/archives/C02Q6KM7F/p1724084895885059

### Use cases

- a shop closes and the OSM POI is deleted. We want to keep its prices and location info, but maybe display a `closed` label ?
- a shop closes, and another reopens in replacement. the OSM POI is updated. These 2 locations will have the same OSM id+type, but we need to differenciate them (if Aldi replaces Franprix, prices for Franprix shouldn't be move to Aldi).

### Todo

- [x] new `Location.osm_version` field
- [x] fetch data from OSM API
- [x] script to init data
- [ ] how to update the data if it changes in OSM ?? (another issue to create)
