### ISSUE TITLE
Stats: Store & update app-wide "total" stats

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices#463]
### Story

When launching the OP app, we could display some overall stats + weekly/ongoing stats.
Instead of calculating them each time, we create a Django app/models to store them + sync with cron every night.

Which stats ?
- see https://prices.openfoodfacts.org/app/stats
- see https://github.com/openfoodfacts/open-prices/discussions/399

### Todo

- [x] new `stats` app + `TotalStats` model
- [x] add to admin
- [x] API endpoint `/api/v1/stats`
- [x] CRON to update stats (every night ?)

**Comment by raphodn** [comment]
````
New stats app

Stats
- price_count & price_barcode_count & price_category_count
- product_count & product_with_price_count
- location_count & location_with_price_count
- proof_count & proof_with_price_count
- user_count & user_with_price_count

Weekly Stats
- price_count
- location_count & location_new_count
- product_count & product_new_count
- proof_count
- user_count & user_new_count
- top 3 users (per price_count)
````

**Comment by raphodn** [comment]
Use https://github.com/lazybird/django-solo to only allow 1 instance of the model

**Comment by raphodn** [comment]
fyi @monsieurtanuki there's now a new endpoint with app-wide total stats
https://prices.openfoodfacts.org/api/docs#/stats

**Comment by monsieurtanuki** [comment]
> fyi @monsieurtanuki there's now a new endpoint with app-wide total stats https://prices.openfoodfacts.org/api/docs#/stats

Thank you @raphodn, I've just created the corresponding issue in off-dart!
