### ISSUE TITLE
Location: fetch OSM POI brand (& logo)

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices#467]
### Story

When adding a new location, we fetch data from Nominatim, but it doesn't have *all* of the POI's fields.

Linked with #388

### How

see 
- OSM query: https://github.com/openfoodfacts/open-prices/wiki/Location-search-&-lookup
- new Location fields

### Logos

Brands could help us start showing shop logos (Carrefour & co). Where to store logos ?
OpenStreetMap https://nsi.guide/ seems to point towards the brands Facebook logos

### Todo

- [x] new `Location.osm_brand` field
- [x] fetch data from OSM API
- [ ] script to init data
- [ ] logo ?

**Comment by raphodn** [comment]
https://github.com/openfoodfacts/openfoodfacts-server/blob/main/taxonomies/unused/stores.txt

**Comment by raphodn** [comment]
Side info : I did this recently
https://forum.openstreetmap.fr/t/aidez-moi-a-lister-rajouter-des-chaines-de-magasins-manquants-dans-nsi/26727

**Comment by raphodn** [comment]
Currently:
- 4376 OSM locations with at least 1 price
- 537 different `osm_brand`

top 10
```
'Lidl': 327,
'Intermarché': 113,
'Carrefour': 96,
'Carrefour Market': 78,
'Carrefour City': 73,
'Auchan': 72,
'REWE': 70,
'Monoprix': 69,
'Super U': 66,
'Franprix': 60,
```

**Comment by raphodn** [comment]
In the frontend I started displaying the location's brand logo. Related issue: https://github.com/openfoodfacts/open-prices-frontend/issues/318
The logos are stored in this separate repo: https://github.com/openfoodfacts/brand-images
But we'll need a mapping file because not all the stored locations are formatted correctly..
And return the logo path directly from the server ?
