### ISSUE TITLE
Price: add new "consumption-related" field on receipts: receipt_quantity

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices#499]
### Story

Linked with  #387

Allow users to input the number bought for a given item.

Say in a receipt I buy 2x Snickers, I will add its price once, but I want to store somewhere the info that it was bought in a larger quantity. This would rather be stored on the Price model. For instance receipt_quantity. Defaults to 1.

### Todo

- [x] new field: receipt_quantity : #498
- [ ] ~API: only return this field to the logged in price owner~ ?
- [x] GDPR: store the quantity when uploading prices : https://github.com/openfoodfacts/open-prices/commit/64fcd8058ae23cfdfcd26b66c8c92ffcc6cf57ff

Frontend integration: see https://github.com/openfoodfacts/open-prices-frontend/issues/974

**Comment by raphodn** [comment]
In #666 I made a change to the field type. We now allow users to store Decimal numbers.
Why? For "raw category" prices, for instance buying 2.5 kg of bananas.
