### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices#541]
A meta-issue to track ongoing and future features 

Useful links:
- Github board: https://github.com/orgs/openfoodfacts/projects/105/views/2
- Weekly meeting notes: https://docs.google.com/document/d/1-OfMAi-cB7mi9_q172EbBCWHkfKDM0zVg4wzULW3pFY/edit

### Backend

- [x] more stats
- [ ] GDPR import. Validata ?

### Frontend

- [x] Improve home page & personal dashboard, access to settings
- [ ] Proof edition
- [ ] Online stores
- [ ] Consumption-related fields (receipt total, product quantity)
- [x] Dark mode
- [ ] Improve search

### Mobile

- [x] Allow reusing existing proofs
- [ ] Adding prices for a product category

### Other

- [ ] Showcase reuses
- [ ] NGI Zero Commons application
- [ ] Start using the Forum more (instead of Slack)
- [ ] Push for taxonomies of shops & brands (Product Opener)

### Backend

- [x] Migrate from FastAPI to Django

todo

### Frontend

- [x] Basic price visualization (map, graph)

### Other

- [x] Open Food Facts days
- [ ] Foodity Open Call (negative)
